### ISSUE TITLE
error sending offer: Post https://127.0.0.1:7777/pub: net/http: invalid header field name 

### ISSUE THREAD

**Issue by Beek813** [rtctunnel/rtctunnel#15]
Hi,

I am trying this code and get the following error:

{"level":"fatal","error":"error sending offer: Post https://127.0.0.1:7777/pub: net/http: invalid header field name \"js.fetch:mode\"","time":"2020-07-16T14:25:28+02:00","message":"failed to open peer connection"}

i am running from windows 10, Running the operator localy with the following command:
operator.exe --bind-addr=127.0.0.1:7777

if i go to the adres http://127.0.0.1:7777/sub i see response in the operator command prompt.

but if i start the rtctunnel with the configuration file:
```
keypair:
  public: 342b2sb2juhsg2389wbvsiudr487rgsidfytw87r
  private: 418b7vbo278ov24bo95ob3vob93bo35vb9o3q4
routes:
- localport: 6661
  localpeer: 342b2sb2juhsg2389wbvsiudr487rgsidfytw87r
  remotepeer: b95o7byo43v59bvb9o578ob5rb3v4b9ov34b93
  remoteport: 9090
signalchannel: operator://192.168.100.99:7777
```

i get the error as mentioned on top. if i stop the operator i get the same error message. 

i cant figure out what i am doing wrong.
